
CREATE DATABASE petshop;
USE petshop;

CREATE TABLE CLIENTE (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(110),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(45),
    ENDERECO VARCHAR(45),
    COMPRA_idCOMPRA INT,
    ANIMAL_DE_ESTIMACAO_idANIMAL_DE_ESTIMACAO INT
);

CREATE TABLE COMPRA (
    idCOMPRA INT PRIMARY KEY,
    CPF VARCHAR(11),
    DATA_COMPRA DATE,
    VALOR_TOTAL DECIMAL(10,2),
    idPRODUTO VARCHAR(45),
    PAGAMENTO_PIX_idPAGAMENTO_PIX INT,
    FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF)
);


CREATE TABLE PRODUTO (
    idPRODUTO INT PRIMARY KEY,
    NOME VARCHAR(145),
    DESCRICAO VARCHAR(245),
    PRECO DECIMAL(10,2),
    QUANTIDADE_ESTOQUE INT
);

CREATE TABLE PAGAMENTO_PIX (
    idPAGAMENTO_PIX INT PRIMARY KEY,
    CHAVE_PIX VARCHAR(145),
    ID_COMPRA INT,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(idCOMPRA)
);

CREATE TABLE COMPRA_has_PRODUTO (
    COMPRA_idCOMPRA INT,
    PRODUTO_idPRODUTO INT,
    PRIMARY KEY (COMPRA_idCOMPRA, PRODUTO_idPRODUTO),
    FOREIGN KEY (COMPRA_idCOMPRA) REFERENCES COMPRA(idCOMPRA),
    FOREIGN KEY (PRODUTO_idPRODUTO) REFERENCES PRODUTO(idPRODUTO)
);

CREATE TABLE FORNECEDOR (
    idFORNECEDOR INT PRIMARY KEY,
    NOME VARCHAR(145),
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(45)
);

CREATE TABLE FORNECEDOR_has_PRODUTO (
    FORNECEDOR_idFORNECEDOR INT,
    PRODUTO_idPRODUTO INT,
    PRIMARY KEY (FORNECEDOR_idFORNECEDOR, PRODUTO_idPRODUTO),
    FOREIGN KEY (FORNECEDOR_idFORNECEDOR) REFERENCES FORNECEDOR(idFORNECEDOR),
    FOREIGN KEY (PRODUTO_idPRODUTO) REFERENCES PRODUTO(idPRODUTO)
);

CREATE TABLE ADMINISTRADOR (
    idADMINISTRADOR INT PRIMARY KEY,
    NOME VARCHAR(45),
    LOGIN VARCHAR(45),
    SENHA VARCHAR(145)
);

CREATE TABLE ADMINISTRADOR_has_PRODUTO (
    ADMINISTRADOR_idADMINISTRADOR INT,
    PRODUTO_idPRODUTO INT,
    PRIMARY KEY (ADMINISTRADOR_idADMINISTRADOR, PRODUTO_idPRODUTO),
    FOREIGN KEY (ADMINISTRADOR_idADMINISTRADOR) REFERENCES ADMINISTRADOR(idADMINISTRADOR),
    FOREIGN KEY (PRODUTO_idPRODUTO) REFERENCES PRODUTO(idPRODUTO)
);


CREATE TABLE ANIMAL_DE_ESTIMACAO (
    idANIMAL_DE_ESTIMACAO INT PRIMARY KEY,
    NOME VARCHAR(45),
    RACA VARCHAR(45),
    IDADE INT,
    SEXO ENUM('M', 'F'),
    CPF_CLIENTE VARCHAR(11),
    FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);


CREATE TABLE SERVICO (
    idSERVICO INT PRIMARY KEY,
    PRECO DECIMAL(10,2),
    BANHO TINYINT,
    TOSA TINYINT
);


CREATE TABLE CLIENTE_has_SERVICO (
    CLIENTE_CPF VARCHAR(11),
    CLIENTE_COMPRA_idCOMPRA INT,
    SERVICO_idSERVICO INT,
    PRIMARY KEY (CLIENTE_CPF, CLIENTE_COMPRA_idCOMPRA, SERVICO_idSERVICO),
    FOREIGN KEY (CLIENTE_CPF) REFERENCES CLIENTE(CPF),
    FOREIGN KEY (CLIENTE_COMPRA_idCOMPRA) REFERENCES COMPRA(idCOMPRA),
    FOREIGN KEY (SERVICO_idSERVICO) REFERENCES SERVICO(idSERVICO)
);
