UPDATE CLIENTE
SET TELEFONE = '61999988877', ENDERECO = 'Rua Nova, 321'
WHERE CPF = '11122233344';

UPDATE PRODUTO
SET PRECO = 199.90, QUANTIDADE_ESTOQUE = 55
WHERE idPRODUTO = 101;

UPDATE ANIMAL_DE_ESTIMACAO
SET NOME = 'Bolinha Feliz', IDADE = 4
WHERE idANIMAL_DE_ESTIMACAO = 1;

UPDATE COMPRA
SET VALOR_TOTAL = 220.00
WHERE idCOMPRA = 201;

UPDATE PAGAMENTO_PIX
SET CHAVE_PIX = 'carlos.lima@email.com'
WHERE idPAGAMENTO_PIX = 301;

UPDATE SERVICO
SET PRECO = 55.00
WHERE idSERVICO = 1;

UPDATE ADMINISTRADOR_has_PRODUTO
SET PRODUTO_idPRODUTO = 104
WHERE ADMINISTRADOR_idADMINISTRADOR = 1 AND PRODUTO_idPRODUTO = 102;

UPDATE CLIENTE_has_SERVICO
SET SERVICO_idSERVICO = 2
WHERE CLIENTE_CPF = '99988877766' AND CLIENTE_COMPRA_idCOMPRA = 203 AND SERVICO_idSERVICO = 3;